import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def run_command(args):
    result = subprocess.run(args, cwd=ROOT, check=False)
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def extract_clip(video_path: Path, clip, output_dir: Path):
    output_dir.mkdir(parents=True, exist_ok=True)
    clip_path = output_dir / f"{clip['clip_id']}.mp4"
    duration = max(0.1, float(clip["duration_seconds"]))
    run_command(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-ss",
            str(clip["time_start"]),
            "-i",
            str(video_path),
            "-t",
            str(duration),
            "-c:v",
            "libx264",
            "-c:a",
            "aac",
            "-y",
            str(clip_path),
        ]
    )
    return clip_path


def main():
    parser = argparse.ArgumentParser(
        description="Process a serve practice video with multiple clips: extract clips and run per-clip analysis."
    )
    parser.add_argument("--input-video", required=True, help="Original serve practice video.")
    parser.add_argument("--clips-json", required=True, help="Clip summary generated by detect-serve-clips.py.")
    parser.add_argument(
        "--provider",
        choices=["stub", "mediapipe"],
        default="stub",
        help="Pose extraction provider for each clip.",
    )
    parser.add_argument("--model-asset-path", help="Path to pose_landmarker.task for mediapipe provider.")
    parser.add_argument(
        "--handedness",
        choices=["right", "left"],
        default="right",
        help="Player handedness.",
    )
    parser.add_argument("--sample-every", type=int, default=1, help="Keep every Nth frame in pose extraction.")
    parser.add_argument(
        "--clips-dir",
        help="Optional directory for extracted clip videos. Defaults to videos/<video-name>_clips",
    )
    parser.add_argument(
        "--analysis-dir",
        default="analysis",
        help="Directory for generated pose and analysis JSON files.",
    )
    parser.add_argument(
        "--skip-summary",
        action="store_true",
        help="Skip training-summary rebuild after processing all clips.",
    )
    args = parser.parse_args()

    input_video = Path(args.input_video)
    clips_json = Path(args.clips_json)
    if not input_video.exists():
        raise SystemExit(f"Input video was not found: {input_video}")
    if not clips_json.exists():
        raise SystemExit(f"Clip summary file was not found: {clips_json}")

    clips_data = load_json(clips_json)
    clips = clips_data.get("clips", [])
    if not clips:
        raise SystemExit("No clips were found in the clip summary JSON.")

    clips_dir = Path(args.clips_dir) if args.clips_dir else Path("videos") / f"{input_video.stem}_clips"
    analysis_dir = Path(args.analysis_dir)
    analysis_dir.mkdir(parents=True, exist_ok=True)

    processed = []
    total = len(clips)

    for index, clip in enumerate(clips, start=1):
        print(f"Processing clip {index}/{total}: {clip['clip_id']}")
        clip_video = extract_clip(input_video, clip, clips_dir)
        pose_output = analysis_dir / f"{clip['clip_id']}-pose.json"
        analysis_output = analysis_dir / f"{clip['clip_id']}-analysis.json"

        cmd = [
            sys.executable,
            str(ROOT / "scripts" / "run-analysis-pipeline.py"),
            "--input-video",
            str(clip_video),
            "--provider",
            args.provider,
            "--action-type",
            "serve",
            "--handedness",
            args.handedness,
            "--sample-every",
            str(args.sample_every),
            "--pose-output",
            str(pose_output),
            "--analysis-output",
            str(analysis_output),
            "--skip-summary",
        ]
        if args.model_asset_path:
            cmd.extend(["--model-asset-path", args.model_asset_path])

        run_command(cmd)

        processed.append(
            {
                "clip_id": clip["clip_id"],
                "clip_video": str(clip_video).replace("\\", "/"),
                "pose_json": str(pose_output).replace("\\", "/"),
                "analysis_json": str(analysis_output).replace("\\", "/"),
                "time_start": clip["time_start"],
                "time_end": clip["time_end"],
                "duration_seconds": clip["duration_seconds"],
            }
        )

    summary_index = analysis_dir / f"{input_video.stem}-batch-analysis.json"
    save_json(
        summary_index,
        {
            "video_file": str(input_video).replace("\\", "/"),
            "provider": args.provider,
            "clip_count": len(processed),
            "clips": processed,
        },
    )
    print(f"Batch analysis index written to: {summary_index}")

    if not args.skip_summary:
        run_command(
            [
                "powershell",
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(ROOT / "scripts" / "build-training-summary.ps1"),
            ]
        )


if __name__ == "__main__":
    main()
